version: '3.7'

services:
  account:
    build:
      args:
        user: ${USER}
      context: ./accounts
      dockerfile: ./accounts/Dockerfile
    image: banking-account
    container_name: banking-account
    ports:
      - 8080:8080

  customer:
    build:
      args:
        user: ${USER}
      context: ./customers
      dockerfile: ./customers/Dockerfile
    image: banking-customer
    container_name: banking-customer
    ports:
      - 8080:8080
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_DATABASE}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  statement:
    build:
      args:
        user: ${USER}
      context: ./statements
      dockerfile: ./statements/Dockerfile
    image: banking-statement
    container_name: banking-statement
    ports:
      - 8080:8080

  db:
    image: mysql:5.7
    container_name: banking-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - banking-customers-data:/var/lib/mysql
    networks:
      - banking-backend

  mongo:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - banking-statements-data:/data/db
    networks:
      - banking-backend

  nginx:
    image: nginx:1.17-alpine
    container_name: banking-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./accounts:/var/sites/accounts
      - ./customers:/var/sites/customers
      - ./statements:/var/sites/statements
      - ./docker/nginx/configs:/etc/nginx/conf.d
    networks:
      - banking-backend

volumes:
  banking-customers-data:
  banking-statements-data:
  banking-accounts-data:

networks:
  banking-backend:
